const express=require('express');const path=require('path');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const helmet=require('helmet');const rateLimit=require('express-rate-limit');require('dotenv').config();
const app=express(),PORT=+(process.env.PORT||3000),SECRET=process.env.JWT_SECRET,OWNER=process.env.OWNER_USERNAME||'owner',OWNER_PASS=process.env.OWNER_PASSWORD;
if(!SECRET||!OWNER_PASS){console.error('Set JWT_SECRET and OWNER_PASSWORD in .env');process.exit(1)}
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'2mb'}));app.use(rateLimit({windowMs:60000,max:180}));
const db=new Database(process.env.DB_FILE||path.join(__dirname,'data.sqlite'));db.pragma('journal_mode=WAL');db.exec(`CREATE TABLE IF NOT EXISTS admins(username TEXT PRIMARY KEY,password_hash TEXT NOT NULL,role TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS users(username TEXT PRIMARY KEY,password_hash TEXT NOT NULL,phone TEXT,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,category TEXT,name TEXT,price INTEGER,image TEXT);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,item_name TEXT,price INTEGER,ign TEXT,buyer TEXT,time TEXT,status TEXT);CREATE TABLE IF NOT EXISTS chats(id TEXT PRIMARY KEY,name TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,thread_id TEXT,sender TEXT,text TEXT,time TEXT,seen_by_admin INTEGER DEFAULT 0,seen_by_user INTEGER DEFAULT 0);`);
const now=()=>new Date().toISOString(),sign=u=>jwt.sign(u,SECRET,{expiresIn:'12h'});function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.replace(/^Bearer /,''),SECRET);next()}catch(e){res.status(401).json({error:'نیاز به ورود دارید'})}}function admin(req,res,next){auth(req,res,()=>['admin','owner'].includes(req.user.role)?next():res.status(403).json({error:'دسترسی مدیر لازم است'}))}function owner(req,res,next){auth(req,res,()=>req.user.role==='owner'?next():res.status(403).json({error:'فقط مالک سایت دسترسی دارد'}))}
if(!db.prepare('SELECT 1 FROM admins WHERE role="owner"').get())db.prepare('INSERT INTO admins VALUES(?,?,?,?)').run(OWNER,bcrypt.hashSync(OWNER_PASS,12),'owner',now());
if(!db.prepare('SELECT 1 FROM products').get()){let i=db.prepare('INSERT INTO products VALUES(?,?,?,?,?)');[['p7','coin','100 VON',20000,''],['p8','coin','500 VON',90000,''],['p9','coin','1200 VON',200000,''],['p10','coin','3000 VON',450000,'']].forEach(x=>i.run(...x))}let si=db.prepare('INSERT OR IGNORE INTO settings VALUES(?,?)');si.run('ip','play.arvon.mc');si.run('whatsapp','989918180709');si.run('tagline','شبکه‌ی بدواز و پرکتیس — سکه اختصاصی VON برای خرید آیتم و امکانات داخل سرور');
const settings=()=>Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]));const products=()=>db.prepare('SELECT * FROM products').all();const orders=()=>db.prepare('SELECT id,item_name itemName,price,ign,buyer,time,status FROM orders ORDER BY time DESC').all();
function thread(id){let t=db.prepare('SELECT * FROM chats WHERE id=?').get(id);if(!t)return null;let ms=db.prepare('SELECT sender AS "from",text,time,seen_by_admin seenByAdmin,seen_by_user seenByUser FROM messages WHERE thread_id=? ORDER BY id').all(id).map(x=>({...x,seenByAdmin:!!x.seenByAdmin,seenByUser:!!x.seenByUser}));return{id:t.id,name:t.name,messages:ms}}
app.get('/api/public/products',(q,r)=>r.json({products:products()}));app.get('/api/public/settings',(q,r)=>r.json({settings:settings()}));
app.post('/api/auth/register',(q,r)=>{let{username,password,phone=''}=q.body||{};if(!/^[A-Za-z0-9_.-]{3,32}$/.test(username||'')||typeof password!=='string'||password.length<8)return r.status(400).json({error:'نام کاربری یا رمز معتبر نیست'});if(db.prepare('SELECT 1 FROM users WHERE username=?').get(username))return r.status(409).json({error:'این نام کاربری قبلا ثبت شده'});db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(username,bcrypt.hashSync(password,12),phone,now());let u={username,role:'user'};r.json({token:sign(u),user:u})});
app.post('/api/auth/login',(q,r)=>{let u=db.prepare('SELECT * FROM users WHERE username=?').get(q.body?.username||'');if(!u||!bcrypt.compareSync(q.body?.password||'',u.password_hash))return r.status(401).json({error:'نام کاربری یا رمز اشتباه است'});let x={username:u.username,role:'user'};r.json({token:sign(x),user:x})});app.get('/api/auth/me',auth,(q,r)=>r.json(q.user));
app.post('/api/admin/login',(q,r)=>{let a=db.prepare('SELECT * FROM admins WHERE username=?').get(q.body?.username||'');if(!a||!bcrypt.compareSync(q.body?.password||'',a.password_hash))return r.status(401).json({error:'نام کاربری یا رمز ادمین اشتباه است'});let u={username:a.username,role:a.role};r.json({token:sign(u),user:u})});
app.get('/api/admin/admins',owner,(q,r)=>r.json({admins:db.prepare('SELECT username,role,created_at FROM admins WHERE role="admin"').all()}));app.post('/api/admin/admins',owner,(q,r)=>{let{username,password}=q.body||{};if(!/^[A-Za-z0-9_.-]{3,32}$/.test(username||'')||typeof password!=='string'||password.length<8)return r.status(400).json({error:'نام کاربری یا رمز معتبر نیست'});if(db.prepare('SELECT 1 FROM admins WHERE username=?').get(username))return r.status(409).json({error:'این ادمین وجود دارد'});db.prepare('INSERT INTO admins VALUES(?,?,?,?)').run(username,bcrypt.hashSync(password,12),'admin',now());r.json({ok:true})});app.delete('/api/admin/admins/:u',owner,(q,r)=>{db.prepare('DELETE FROM admins WHERE username=? AND role="admin"').run(q.params.u);r.json({ok:true})});
app.put('/api/admin/settings',owner,(q,r)=>{let{ip,whatsapp,tagline,newPassword}=q.body||{};if(!ip||!/^[0-9]+$/.test(whatsapp||''))return r.status(400).json({error:'IP و شماره تماس را درست وارد کنید'});let u=db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');u.run('ip',ip);u.run('whatsapp',whatsapp);u.run('tagline',tagline||'');if(newPassword){if(newPassword.length<8)return r.status(400).json({error:'رمز باید حداقل ۸ کاراکتر باشد'});db.prepare('UPDATE admins SET password_hash=? WHERE role="owner"').run(bcrypt.hashSync(newPassword,12))}r.json({settings:settings()})});
app.put('/api/admin/products',admin,(q,r)=>{let list=Array.isArray(q.body?.products)?q.body.products:[];let tx=db.transaction(()=>{db.prepare('DELETE FROM products').run();let i=db.prepare('INSERT INTO products VALUES(?,?,?,?,?)');for(let p of list)if(p.id&&p.name)i.run(String(p.id),String(p.category||'coin'),String(p.name),+p.price||0,String(p.image||''))});tx();r.json({products:products()})});
app.post('/api/orders',(q,r)=>{let{itemName,price,ign,buyer=null}=q.body||{};if(!itemName||!ign)return r.status(400).json({error:'اطلاعات سفارش ناقص است'});let id='o'+Date.now()+Math.floor(Math.random()*999);db.prepare('INSERT INTO orders VALUES(?,?,?,?,?,?,?)').run(id,itemName,+price||0,ign,buyer,now(),'pending');r.json({ok:true,id})});app.get('/api/admin/orders',admin,(q,r)=>r.json({orders:orders()}));app.put('/api/admin/orders',admin,(q,r)=>r.json({ok:true}));app.patch('/api/admin/orders/:id',admin,(q,r)=>{db.prepare("UPDATE orders SET status=CASE WHEN status='done' THEN 'pending' ELSE 'done' END WHERE id=?").run(q.params.id);r.json({orders:orders()})});app.delete('/api/admin/orders/:id',admin,(q,r)=>{db.prepare('DELETE FROM orders WHERE id=?').run(q.params.id);r.json({orders:orders()})});
function access(q,id){return ['admin','owner'].includes(q.user.role)||id==='u_'+q.user.username||id.startsWith('g_')}
app.get('/api/chats/:id',auth,(q,r)=>access(q,q.params.id)?r.json({thread:thread(q.params.id)}):r.status(403).json({error:'دسترسی ندارید'}));app.post('/api/chats/:id',auth,(q,r)=>{let id=q.params.id;if(!access(q,id))return r.status(403).json({error:'دسترسی ندارید'});if(!db.prepare('SELECT 1 FROM chats WHERE id=?').get(id))db.prepare('INSERT INTO chats VALUES(?,?,?)').run(id,String(q.body?.name||id).slice(0,80),now());if(q.body?.text)db.prepare('INSERT INTO messages(thread_id,sender,text,time,seen_by_admin,seen_by_user) VALUES(?,?,?,?,?,?)').run(id,['admin','owner'].includes(q.user.role)?'admin':'user',String(q.body.text).slice(0,4000),now(),['admin','owner'].includes(q.user.role)?1:0,['admin','owner'].includes(q.user.role)?0:1);r.json({thread:thread(id)})});app.patch('/api/chats/:id/seen',auth,(q,r)=>{let id=q.params.id;if(!access(q,id))return r.status(403).json({error:'دسترسی ندارید'});if(q.body?.who==='admin')db.prepare('UPDATE messages SET seen_by_admin=1 WHERE thread_id=? AND sender="user"').run(id);if(q.body?.who==='user')db.prepare('UPDATE messages SET seen_by_user=1 WHERE thread_id=? AND sender="admin"').run(id);r.json({thread:thread(id)})});app.get('/api/admin/chats',admin,(q,r)=>{let o={};for(let x of db.prepare('SELECT id FROM chats').all())o[x.id]=thread(x.id);r.json({chats:o})});
app.use(express.static(__dirname));app.get('*',(q,r)=>q.path.startsWith('/api/')?r.status(404).json({error:'Not found'}):r.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,()=>console.log('ARVON running on '+PORT));
